### ISSUE TITLE
Steam Deck

### ISSUE THREAD

**Issue by wilk09** [Traducciones-Kurain/AATrilogy-2019-ESP#4]
Podéis poner instrucciones para poder instalar la tradu en una steam deck?

Gracias!

**Comment by mmgmp** [comment]
Lo primero MUCHAS gracias por la maravillosa traducción, sin embargo...

Me aparece este error al intentar ejecutarlo: 
`No usable version of libssl was found` 
Cuando tengo instalado **libssl3 ver. 3.0.2-0ubuntu1.10 [Ubuntu/jammy main]** 

¿Tiene que ser una versión concreta de la librería?
Agradecería cualquier info acerca del parche de Linux.

Gracias

**Comment by WorstAquaPlayer** [comment]
> Podéis poner instrucciones para poder instalar la tradu en una steam deck?
> 
> Gracias!

El parcheador ahora puede ser compilado y abierto desde Linux. Las instrucciones fueron actualizadas tanto en el repositorio como en la página de release.

**Comment by WorstAquaPlayer** [comment]
> Lo primero MUCHAS gracias por la maravillosa traducción, sin embargo...
> 
> Me aparece este error al intentar ejecutarlo: `No usable version of libssl was found` Cuando tengo instalado **libssl3 ver. 3.0.2-0ubuntu1.10 [Ubuntu/jammy main]**
> 
> ¿Tiene que ser una versión concreta de la librería? Agradecería cualquier info acerca del parche de Linux.
> 
> Gracias

Se necesita tener una versión de libssl específica, el **libssl1.0-dev**. En mis pruebas utilicé Ubuntu y tuve que instalar esa versión.

Poniendo estos comandos en la terminal, puedes descargar esta librería:
```
sudo add-apt-repository ppa:rael-gc/rvm
sudo apt-get update
sudo apt install libssl1.0-dev
```

Fuente: https://stackoverflow.com/a/73066454

**Comment by mmgmp** [comment]
Gracias, ahora si arranca el programa, pero me dice que no detecta el juego, cuando lo tengo instalado el la carpeta por defecto de Steam Flatpak, que es:

`/home/marcos/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Phoenix Wright Ace Attorney Trilogy`

¿Donde esta mirando en busca del juego, funcionaria con un enlace simbólico?

Gracias

**Comment by WorstAquaPlayer** [comment]
Perdón por la tardanza, pero el parcheador fue actualizado para poder detectar la carpeta de Steam Flatpak, dejo el issue abierto para que me comentes si a ti tambien te funciono.

**Comment by WorstAquaPlayer** [comment]
> Detecta perfectamente la version de flatpak, gracias por la actualización. Lo único lo de la dependencia del libssl, no soy desarrollador, pero no se podría hacer algo para remediarlo?
> 
> Gracias aun así por el soporte a la version de Linux!!!

Así como está ahora, no. El Avalonia que se utiliza ahora mismo usa .NET 5, y según [este comentario del mismo post de StackOverflow](https://stackoverflow.com/a/72881516), a partir de cierta versión de Ubuntu, la librería que viene es una más actualizada y no compatible con el parche.

Lo ideal sería actualizar el parcheador entero para que soporte versiones de .NET más nuevas, y de paso refactorizarlo un poco porque admito que algunas partes no son de lo mejor visualmente.
